const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const R=require('../functions/core');
function harness(){
  const store=new Map([['admins/staff',{nombre:'Equipo'}],['caja/'+R.day(),{efectivoInicial:10000,cerrado:false}]]);let sequence=0,abortCommit=false;
  const copy=x=>x===undefined?undefined:structuredClone(x);
  const ref=p=>({path:p,id:p.split('/').at(-1),get:async()=>snap(p,store)});
  const snap=(p,map)=>({id:p.split('/').at(-1),ref:ref(p),exists:map.has(p),data:()=>copy(map.get(p))});
  function query(name,filters=[]){return {name,filters,where:(field,op,value)=>query(name,[...filters,[field,op,value]]),doc:(id)=>ref(name+'/'+(id||`generated-${++sequence}`))};}
  let chain=Promise.resolve();
  const db={doc:ref,collection:query,runTransaction:fn=>{const task=chain.then(async()=>{const working=new Map([...store].map(([k,v])=>[k,copy(v)]));let wrote=false;
    const tx={get:async target=>{assert.equal(wrote,false,'Firestore requiere todas las lecturas antes de escribir');if(target.path)return snap(target.path,working);const docs=[...working.keys()].filter(p=>p.startsWith(target.name+'/')&&p.split('/').length===2).filter(p=>target.filters.every(([field,op,value])=>op==='=='?working.get(p)[field]===value:value.includes(working.get(p)[field]))).map(p=>snap(p,working));return {docs,size:docs.length,empty:!docs.length,forEach:fn=>docs.forEach(fn)};},set:(r,v,opts)=>{wrote=true;working.set(r.path,opts?.merge?{...working.get(r.path),...copy(v)}:copy(v));},create:(r,v)=>{wrote=true;if(working.has(r.path))throw Error('Already exists');working.set(r.path,copy(v));},update:(r,v)=>{wrote=true;if(!working.has(r.path))throw Error('Not found');working.set(r.path,{...working.get(r.path),...copy(v)});},delete:r=>{wrote=true;working.delete(r.path);}};
    const result=await fn(tx);if(abortCommit){abortCommit=false;throw Error('Simulated commit failure');}store.clear();working.forEach((v,k)=>store.set(k,v));return result;});chain=task.catch(()=>{});return task;}};
  class HttpsError extends Error{constructor(code,message){super(message);this.code=code;}}
  const exports={};const context={exports,console:{error(){}},Date,require:name=>name==='firebase-functions/v2/https'?{onCall:(_,fn)=>fn,HttpsError}:name==='firebase-admin/app'?{initializeApp(){}}:name==='firebase-admin/firestore'?{getFirestore:()=>db}:name==='./core'?R:require(name)};
  vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../functions/index.js'),'utf8'),context);
  const call=(name,data,uid='staff')=>exports[name]({data,auth:uid?{uid}:null});
  return {store,call,abort:()=>abortCommit=true};
}
async function order(h,selection={pollo:3,fries:1,jalapeno:1,cola:1},mesaId='mesa-1',requestId='request-1',uid='customer'){return h.call('crearPedido',{selection,mesaId,requestId},uid);}
async function ready(h,id){for(const field of ['entranteLista','comidaLista','bebidaLista'])if(R.requirements(h.store.get('pedidos/'+id))[field])await h.call('adminAccion',{action:'listo',id,field});}
test('sin sesión y sin permiso de administrador no se pueden mutar datos',async()=>{const h=harness();await assert.rejects(h.call('crearPedido',{mesaId:'mesa-1',requestId:'test',selection:{pollo:3}},null),e=>e.code==='unauthenticated');await assert.rejects(h.call('adminAccion',{action:'cajaCerrar',amount:100},'customer'),e=>e.code==='permission-denied');});
test('servidor recalcula total, clasifica y evita pedido duplicado por reintento',async()=>{const h=harness(),p=await order(h);assert.equal(p.total,1750);const again=await order(h);assert.equal(p.id,again.id);assert.equal([...h.store.keys()].filter(k=>k.startsWith('pedidos/')).length,1);assert.deepEqual(R.requirements(h.store.get('pedidos/'+p.id)),{entranteLista:true,comidaLista:true,bebidaLista:true});});
test('no se puede cobrar sin terminar entrantes, comida y bebidas',async()=>{const h=harness(),p=await order(h);await assert.rejects(h.call('adminAccion',{action:'cobrar',id:p.id,metodo:'efectivo'}));await ready(h,p.id);assert.equal(h.store.get('pedidos/'+p.id).estado,'realizado');});
test('dos cobros simultáneos registran un único ingreso',async()=>{const h=harness(),p=await order(h);await ready(h,p.id);await Promise.all([h.call('adminAccion',{action:'cobrar',id:p.id,metodo:'efectivo'}),h.call('adminAccion',{action:'cobrar',id:p.id,metodo:'efectivo'})]);assert.equal(h.store.get('pagos/'+p.id).total,1750);assert.equal([...h.store.keys()].filter(k=>k.startsWith('pagos/')).length,1);});
test('fallo del commit no deja pedido pagado sin ingreso',async()=>{const h=harness(),p=await order(h);await ready(h,p.id);h.abort();await assert.rejects(h.call('adminAccion',{action:'cobrar',id:p.id,metodo:'efectivo'}));assert.equal(h.store.get('pedidos/'+p.id).estado,'realizado');assert.equal(h.store.has('pagos/'+p.id),false);});
test('caja cerrada bloquea cobro y anulación de ingresos',async()=>{const h=harness(),p=await order(h);await ready(h,p.id);await h.call('adminAccion',{action:'cajaCerrar',amount:10000});await assert.rejects(h.call('adminAccion',{action:'cobrar',id:p.id,metodo:'paypay'}));await h.call('adminAccion',{action:'cajaReabrir',motivo:'Revisión de caja'});await h.call('adminAccion',{action:'cobrar',id:p.id,metodo:'paypay'});await h.call('adminAccion',{action:'cajaCerrar',amount:10000});await assert.rejects(h.call('adminAccion',{action:'anularCobro',id:p.id,motivo:'Error de pago'}));});
test('papelera restaura pedido y borrar conserva ingresos',async()=>{const h=harness(),p=await order(h);await ready(h,p.id);await h.call('adminAccion',{action:'cobrar',id:p.id,metodo:'efectivo'});await h.call('adminAccion',{action:'borrar',id:p.id,motivo:'Comanda de prueba'});assert.equal(h.store.has('pedidos/'+p.id),false);assert.equal(h.store.has('pagos/'+p.id),true);assert.equal(h.store.has('papelera/'+p.id),true);await h.call('adminAccion',{action:'restaurar',id:p.id,motivo:'Recuperación de prueba'});assert.equal(h.store.get('pedidos/'+p.id).estado,'pagado');assert.equal(h.store.has('papelera/'+p.id),false);});
test('anular ingreso reabre el pedido y deja registro de auditoría',async()=>{const h=harness(),p=await order(h);await ready(h,p.id);await h.call('adminAccion',{action:'cobrar',id:p.id,metodo:'efectivo'});await h.call('adminAccion',{action:'anularCobro',id:p.id,motivo:'Método equivocado'});assert.equal(h.store.get('pedidos/'+p.id).estado,'realizado');assert.equal(h.store.has('pagos/'+p.id),false);assert.ok([...h.store.values()].some(d=>d.action==='anularCobro'&&d.before?.total===1750));});
test('corregir recalcula importe, mueve mesa y reinicia preparación',async()=>{const h=harness(),p=await order(h);await ready(h,p.id);await h.call('adminAccion',{action:'corregir',id:p.id,mesaId:'silla-10',selection:{fries:2,masa:1},motivo:'Corrección de productos'});const saved=h.store.get('pedidos/'+p.id);assert.equal(saved.total,700);assert.equal(saved.mesaId,'silla-10');assert.equal(saved.estado,'pendiente');assert.equal(saved.comidaLista,false);assert.equal(saved.entranteLista,false);});
test('liberar mesa antigua en japonés cancela sin crear cobro',async()=>{const h=harness();h.store.set('pedidos/legacy',{mesa:'テーブル 1',tacos:['3x pollo'],extras:['1x fries'],estado:'pendiente',total:1500});await h.call('adminAccion',{action:'liberarMesa',mesaId:'mesa-1',motivo:'Pedido de prueba antiguo'});assert.equal(h.store.get('pedidos/legacy').estado,'cancelado');assert.equal([...h.store.keys()].filter(k=>k.startsWith('pagos/')).length,0);});
test('completar secciones casi simultáneamente mantiene todos los indicadores',async()=>{const h=harness(),p=await order(h);await Promise.all(['entranteLista','comidaLista','bebidaLista'].map(field=>h.call('adminAccion',{action:'listo',id:p.id,field})));assert.equal(h.store.get('pedidos/'+p.id).estado,'realizado');});
test('stock y carta nuevos se validan en el servidor',async()=>{const h=harness();await h.call('adminAccion',{action:'stock',productId:'pollo',disponible:false});await assert.rejects(order(h));const products=[...R.CATALOG,{id:'croquetas',category:'entrante',price:500,names:{es:'Croquetas',en:'Croquettes',ja:'コロッケ'},active:true}];await h.call('adminAccion',{action:'guardarCarta',products});assert.equal(h.store.get('config/menu').products.at(-1).category,'entrante');await assert.rejects(h.call('adminAccion',{action:'guardarCarta',products:[...products,products[0]]}));});
test('pedido adicional reconoce mesa antigua y permite solo bebida',async()=>{const h=harness();h.store.set('pedidos/legacy',{mesa:'Table 1',estado:'pendiente',tacos:['3x pollo'],total:1200});const p=await order(h,{cola:1});assert.equal(p.total,200);assert.equal(h.store.get('pedidos/'+p.id).pedidoDeSeguimiento,true);});
test('cambio de precios exige volver a revisar la comanda',async()=>{const h=harness();await assert.rejects(h.call('crearPedido',{mesaId:'mesa-1',requestId:'quote-old',selection:{pollo:3,cola:1},expectedTotal:1300},'customer'));assert.equal([...h.store.keys()].filter(k=>k.startsWith('pedidos/')).length,0);});
