const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{createRequire}=require('node:module');
const req=require;
const {initializeTestEnvironment,assertFails,assertSucceeds}=req('@firebase/rules-unit-testing'),F=req('firebase/firestore');
const Spark=require('../public/spark'),R=require('../public/core');
const projectId='demo-rocio-spark';let env,sequence=0;
F.setLogLevel('silent');
const id=()=>`00000000-0000-4000-8000-${String(++sequence).padStart(12,'0')}`;
function adapter(db){
  const wrap=s=>({id:s.id,exists:s.exists(),ref:ref(s.ref),data:()=>s.data()});
  const page=s=>({docs:s.docs.map(wrap),size:s.size,forEach:fn=>s.docs.map(wrap).forEach(fn)});
  const ref=r=>({raw:r,path:r.path,id:r.id,get:async()=>wrap(await F.getDoc(r))});
  const query=(name,filters=[])=>({where:(field,op,value)=>query(name,[...filters,F.where(field,op,value)]),get:async()=>page(await F.getDocs(F.query(F.collection(db,name),...filters))),doc:key=>ref(key?F.doc(db,name,key):F.doc(F.collection(db,name)))});
  const write=(tx)=>({get:async r=>wrap(await tx.get(r.raw)),set:(r,v)=>tx.set(r.raw,v),delete:r=>tx.delete(r.raw),commit:()=>tx.commit()});
  return {doc:name=>ref(F.doc(db,name)),collection:query,batch:()=>write(F.writeBatch(db)),runTransaction:fn=>F.runTransaction(db,tx=>fn(write(tx)))};
}
const engine=(uid=null)=>Spark.create(adapter((uid?env.authenticatedContext(uid):env.unauthenticatedContext()).firestore()),{currentUser:uid?{uid}:null},F.serverTimestamp);
async function seed(){await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();await F.setDoc(F.doc(db,'admins/staff'),{nombre:'Prueba'});await F.setDoc(F.doc(db,'caja/'+R.day()),{efectivoInicial:10000,cerrado:false});});await engine('staff').init();}
const order=(service,selection={pollo:3,fries:1,jalapeno:1,cola:1},mesaId='mesa-1',requestId=id())=>service.call('crearPedido',{selection,mesaId,requestId});
async function ready(staff,id){for(const field of ['entranteLista','comidaLista','bebidaLista'])await staff.call('adminAccion',{action:'listo',id,field});}
test.before(async()=>{env=await initializeTestEnvironment({projectId,firestore:{host:'127.0.0.1',port:Number(process.env.FIRESTORE_EMULATOR_PORT||8080),rules:fs.readFileSync(path.resolve(__dirname,'../firestore.rules'),'utf8')}});});
test.after(async()=>{await env?.cleanup();});
test.beforeEach(seed);
test('cliente sin sesión crea pedido y consulta solo el estado público de su mesa',async()=>{const customer=engine(),p=await order(customer);assert.equal(p.total,1750);assert.deepEqual(await customer.call('mesaEstado',{mesaId:'mesa-1'}),{abierta:true});const db=env.unauthenticatedContext().firestore();await assertFails(F.getDoc(F.doc(db,'pedidos/'+p.id)));await assertFails(F.getDocs(F.collection(db,'pedidos')));await assertFails(F.getDocs(F.collection(db,'pagos')));});
test('reintentar no duplica pedidos; conserva recibo después de borrar',async()=>{const c=engine(),staff=engine('staff'),rid=id(),a=await order(c,undefined,undefined,rid),b=await order(c,undefined,undefined,rid);assert.equal(a.id,b.id);await staff.call('adminAccion',{action:'borrar',id:a.id,motivo:'Prueba de reintento'});await order(c,undefined,undefined,rid);const rows=await F.getDocs(F.collection(env.authenticatedContext('staff').firestore(),'pedidos'));assert.equal(rows.size,0);});
test('pedido adicional permite bebida; cobrar y anular actualizan ocupación',async()=>{const c=engine(),staff=engine('staff'),p=await order(c);await ready(staff,p.id);const extra=await order(c,{cola:1});assert.equal(extra.total,200);await staff.call('adminAccion',{action:'cancelar',id:extra.id,motivo:'Prueba bebida'});await staff.call('adminAccion',{action:'cobrar',id:p.id,metodo:'efectivo'});assert.equal((await c.call('mesaEstado',{mesaId:'mesa-1'})).abierta,false);await staff.call('adminAccion',{action:'anularCobro',id:p.id,motivo:'Prueba anulación'});assert.equal((await c.call('mesaEstado',{mesaId:'mesa-1'})).abierta,true);});
test('cobros simultáneos no duplican ingresos y caja cerrada bloquea cobro',async()=>{const c=engine(),staff=engine('staff'),p=await order(c);await ready(staff,p.id);await Promise.all([staff.call('adminAccion',{action:'cobrar',id:p.id,metodo:'paypay'}),staff.call('adminAccion',{action:'cobrar',id:p.id,metodo:'paypay'})]);assert.equal((await F.getDocs(F.collection(env.authenticatedContext('staff').firestore(),'pagos'))).size,1);await staff.call('adminAccion',{action:'cajaCerrar',amount:10000});await assert.rejects(staff.call('adminAccion',{action:'anularCobro',id:p.id,motivo:'Caja cerrada'}));});
test('borrar y restaurar recuperan pedido y ocupación; corregir cambia ubicación',async()=>{const c=engine(),staff=engine('staff'),p=await order(c);await staff.call('adminAccion',{action:'borrar',id:p.id,motivo:'Prueba papelera'});assert.equal((await c.call('mesaEstado',{mesaId:'mesa-1'})).abierta,false);await staff.call('adminAccion',{action:'restaurar',id:p.id,motivo:'Prueba recuperar'});assert.equal((await c.call('mesaEstado',{mesaId:'mesa-1'})).abierta,true);await staff.call('adminAccion',{action:'corregir',id:p.id,mesaId:'silla-10',selection:{fries:1},motivo:'Prueba corregir'});assert.equal((await c.call('mesaEstado',{mesaId:'mesa-1'})).abierta,false);assert.equal((await c.call('mesaEstado',{mesaId:'silla-10'})).abierta,true);await staff.call('adminAccion',{action:'liberarMesa',mesaId:'silla-10',motivo:'Prueba liberar'});assert.equal((await c.call('mesaEstado',{mesaId:'silla-10'})).abierta,false);});
test('stock y futuros entrantes se aplican a pedidos públicos',async()=>{const c=engine(),staff=engine('staff');await staff.call('adminAccion',{action:'stock',productId:'pollo',disponible:false});await assert.rejects(order(c));const products=[...R.CATALOG,{id:'croquetas',category:'entrante',price:500,names:{es:'Croquetas',en:'Croquettes',ja:'コロッケ'},active:true}];await staff.call('adminAccion',{action:'guardarCarta',products});assert.equal((await order(c,{carnitas:3,croquetas:1})).total,1700);});
async function forged(modify){const db=env.unauthenticatedContext().firestore(),rid=id(),items=Spark.orderItems(R.calculate({pollo:3}).items),now=F.serverTimestamp();const d={schemaVersion:3,requestId:rid,mesaId:'mesa-1',mesa:'Mesa 1',items,productIds:items.map(i=>i.id),total:1200,estado:'pendiente',fecha:new Date().toISOString(),createdAt:now,entranteLista:false,comidaLista:false,bebidaLista:false,horaEntranteLista:null,horaComidaLista:null,horaBebidaLista:null,horaPagado:null,metodoPago:null,pedidoDeSeguimiento:false};modify(d);const b=F.writeBatch(db);b.set(F.doc(db,'pedidos/'+rid),d);b.set(F.doc(db,'solicitudes/'+rid),{idPedido:rid,total:d.total,createdAt:now});b.set(F.doc(db,'mesas/mesa-1'),{openCount:1,abierta:true,revision:2,updatedAt:now,requestId:rid});return b.commit();}
test('reglas rechazan total/precio falsificado, pedido vacío, duplicados y estado cobrado',async()=>{for(const alter of [d=>d.total=1,d=>{d.items[0].unitPrice=1;d.total=3;},d=>{d.items=[];d.productIds=[];d.total=0;},d=>d.estado='pagado',d=>{d.items.push({...d.items[0]});d.productIds.push('pollo');d.total=2400;},d=>{d.items[0].quantity=2;d.total=800;},d=>d.items[0].category='bebida',d=>d.items[0].names.es='Falso',d=>d.pedidoDeSeguimiento=true])await assertFails(forged(alter));});
test('reglas rechazan crear recibo/mesa aislados y modificar/borrar pedidos privados',async()=>{const db=env.unauthenticatedContext().firestore();await assertFails(F.setDoc(F.doc(db,'solicitudes/'+id()),{idPedido:'inventado',total:1,createdAt:F.serverTimestamp()}));await assertFails(F.setDoc(F.doc(db,'mesas/mesa-1'),{openCount:1,abierta:true,revision:2,updatedAt:F.serverTimestamp(),requestId:id()}));const p=await order(engine());await assertFails(F.updateDoc(F.doc(db,'pedidos/'+p.id),{total:1}));await assertFails(F.deleteDoc(F.doc(db,'pedidos/'+p.id)));await assertFails(F.setDoc(F.doc(db,'admins/intruso'),{nombre:'Intruso'}));await assert.rejects(engine('intruso').call('adminAccion',{action:'cajaCerrar',amount:0}));});
test('reglas admiten todos los productos actuales en un pedido',async()=>{const selection=Object.fromEntries(R.CATALOG.map(p=>[p.id,p.category==='comida'?1:1]));const p=await order(engine(),selection);assert.ok(p.total>0);});
test('20 productos distintos y 100 unidades cumplen las reglas',async()=>{const products=[...R.CATALOG,...[1,2,3].map(n=>({id:'nuevo'+n,category:'entrante',price:500,names:{es:'Nuevo '+n,en:'New '+n,ja:'Nuevo '+n},active:true}))];await engine('staff').call('adminAccion',{action:'guardarCarta',products});const selection=Object.fromEntries(products.map(p=>[p.id,5]));assert.ok((await order(engine(),selection)).total>0);});
test('pedido completo rechaza falsificaciones en todas las partes y omitir mesa o recibo',async()=>{const staff=engine('staff'),db=env.unauthenticatedContext().firestore();await order(engine(),Object.fromEntries(R.CATALOG.map(p=>[p.id,1])));const snap=await F.getDocs(F.collection(env.authenticatedContext('staff').firestore(),'pedidos'));const base=snap.docs[0].data();for(const pos of [0,8,16]){const d=structuredClone({...base,createdAt:null});const rid=id();d.requestId=rid;d.pedidoDeSeguimiento=true;d.createdAt=F.serverTimestamp();d.items[pos].unitPrice=1;const batch=F.writeBatch(db);batch.set(F.doc(db,'pedidos/'+rid),d);batch.set(F.doc(db,'solicitudes/'+rid),{idPedido:rid,total:d.total,createdAt:F.serverTimestamp()});batch.set(F.doc(db,'mesas/mesa-1'),{openCount:2,abierta:true,revision:3,updatedAt:F.serverTimestamp(),requestId:rid});await assertFails(batch.commit());}for(const omit of ['mesas','solicitudes']){const rid=id(),d={...base,requestId:rid,pedidoDeSeguimiento:true,createdAt:F.serverTimestamp()},batch=F.writeBatch(db);batch.set(F.doc(db,'pedidos/'+rid),d);if(omit!=='solicitudes')batch.set(F.doc(db,'solicitudes/'+rid),{idPedido:rid,total:d.total,createdAt:F.serverTimestamp()});if(omit!=='mesas')batch.set(F.doc(db,'mesas/mesa-1'),{openCount:2,abierta:true,revision:3,updatedAt:F.serverTimestamp(),requestId:rid});await assertFails(batch.commit());}assert.equal((await F.getDocs(F.collection(env.authenticatedContext('staff').firestore(),'pedidos'))).size,1);});
